// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB58pXUmwnaF32InfvK2ZLdWe0AUcpxWW4',
    appId: '1:817326093729:web:9801c2524cac0ce5e1c7e0',
    messagingSenderId: '817326093729',
    projectId: 'connecthub-1c34f',
    authDomain: 'connecthub-1c34f.firebaseapp.com',
    storageBucket: 'connecthub-1c34f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm0QhVL_ExxY1Mg5QydihcaxZpdM3Vu0o',
    appId: '1:817326093729:android:ed522d01009a0010e1c7e0',
    messagingSenderId: '817326093729',
    projectId: 'connecthub-1c34f',
    storageBucket: 'connecthub-1c34f.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCjUyz-6uMxY-oIbS-5ReLy_6Bi0o-L8w',
    appId: '1:817326093729:ios:7cff12f5dec23564e1c7e0',
    messagingSenderId: '817326093729',
    projectId: 'connecthub-1c34f',
    storageBucket: 'connecthub-1c34f.appspot.com',
    iosClientId: '817326093729-ga7virqvvnmek9bnm0piujra8h0kfua7.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCjUyz-6uMxY-oIbS-5ReLy_6Bi0o-L8w',
    appId: '1:817326093729:ios:7cff12f5dec23564e1c7e0',
    messagingSenderId: '817326093729',
    projectId: 'connecthub-1c34f',
    storageBucket: 'connecthub-1c34f.appspot.com',
    iosClientId: '817326093729-ga7virqvvnmek9bnm0piujra8h0kfua7.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB58pXUmwnaF32InfvK2ZLdWe0AUcpxWW4',
    appId: '1:817326093729:web:ededa9784a613acde1c7e0',
    messagingSenderId: '817326093729',
    projectId: 'connecthub-1c34f',
    authDomain: 'connecthub-1c34f.firebaseapp.com',
    storageBucket: 'connecthub-1c34f.appspot.com',
  );

}